<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'email' => "john.doe@example.com",
                'nik' => "1234567890123",
                'nisn' => "987654321",
                'nipd' => "111223344",
                'full_name' => "John Doe",
                'gender' => "Laki-laki",
                'phone_number' => "081234567890",
                'address' => "Jalan. Merdeka No. 123",
                'religion' => "Protestant",
                'nama_rombel' => "XII IPA 2",
                'violation_score' => 2,
                'score' => 85,
                'register_type' => "Online",
                'school_origin' => "SMA Negeri 1",
                'birth_location' => "Jakarta",
                'birth_date' => "2003-05-15",
                'father_name' => "Robert Doe",
                'father_job' => "Engineer",
                'mother_name' => "Emily Doe",
                'mother_job' => "Teacher",
                'guardian_name' => null,
                'guardian_job' => null,
                'anak_keberapa' => 1,
                'height' => 170,
                'weight' => 60,
                'semester' => "Genap",
                'tingkat_pendidikan' => 12,
                'kurikulum' => "KTSP",
                'kebutuhan_khusus' => "Tidak ada",
            ],
            [
                'email' => "jane.smith@example.com",
                'nik' => "9876543210987",
                'nisn' => "123456789",
                'nipd' => "554433221",
                'full_name' => "Jane Smith",
                'gender' => "Perempuan",
                'phone_number' => "087654321098",
                'address' => "Jalan. Cendrawasih No. 45",
                'religion' => "Catholic",
                'nama_rombel' => "X IPS 3",
                'violation_score' => 1,
                'score' => 92,
                'register_type' => "Offline",
                'school_origin' => "SMA Negeri 2",
                'birth_location' => "Bandung",
                'birth_date' => "2002-08-20",
                'father_name' => "Michael Smith",
                'father_job' => "Doctor",
                'mother_name' => "Olivia Smith",
                'mother_job' => "Architect",
                'guardian_name' => "George Smith",
                'guardian_job' => "Business Owner",
                'anak_keberapa' => 2,
                'height' => 160,
                'weight' => 50,
                'semester' => "Ganjil",
                'tingkat_pendidikan' => 11,
                'kurikulum' => "K13",
                'kebutuhan_khusus' => "Tidak ada",
            ],
            [
                'email' => "alex.johnson@example.com",
                'nik' => "8765432109876",
                'nisn' => "456789012",
                'nipd' => "998877665",
                'full_name' => "Alex Johnson",
                'gender' => "Laki-laki",
                'phone_number' => "081122334455",
                'address' => "Jalan. Harapan Indah No. 67",
                'religion' => "Buddhist",
                'nama_rombel' => "XI IPA 4",
                'violation_score' => 0,
                'score' => 78,
                'register_type' => "Online",
                'school_origin' => "SMA Negeri 3",
                'birth_location' => "Surabaya",
                'birth_date' => "2004-03-10",
                'father_name' => "David Johnson",
                'father_job' => "Businessman",
                'mother_name' => "Sophia Johnson",
                'mother_job' => "Lawyer",
                'guardian_name' => null,
                'guardian_job' => null,
                'anak_keberapa' => 3,
                'height' => 175,
                'weight' => 65,
                'semester' => "Genap",
                'tingkat_pendidikan' => 10,
                'kurikulum' => "KTSP",
                'kebutuhan_khusus' => "Tidak ada",
            ],
            [
                'email' => "aisha.rahman@example.com",
                'nik' => "1111222233334",
                'nisn' => "555444333",
                'nipd' => "777888999",
                'full_name' => "Aisha Rahman",
                'gender' => "Perempuan",
                'phone_number' => "089876543210",
                'address' => "Jalan. Bahagia Sejahtera No. 89",
                'religion' => "Islam",
                'nama_rombel' => "XII IPS 1",
                'violation_score' => 3,
                'score' => 88,
                'register_type' => "Offline",
                'school_origin' => "SMA Negeri 4",
                'birth_location' => "Yogyakarta",
                'birth_date' => "2003-12-05",
                'father_name' => "Ahmed Rahman",
                'father_job' => "Engineer",
                'mother_name' => "Fatima Rahman",
                'mother_job' => "Nurse",
                'guardian_name' => "Ali Rahman",
                'guardian_job' => "Professor",
                'anak_keberapa' => 2,
                'height' => 162,
                'weight' => 55,
                'semester' => "Ganjil",
                'tingkat_pendidikan' => 11,
                'kurikulum' => "K13",
                'kebutuhan_khusus' => "Tidak ada",
            ],
            [
                'email' => "david.miller@example.com",
                'nik' => "3333222211110",
                'nisn' => "222211110",
                'nipd' => "333444555",
                'full_name' => "David Miller",
                'gender' => "Laki-laki",
                'phone_number' => "087712345678",
                'address' => "Jalan. Indah Permai No. 12",
                'religion' => "Hindu",
                'nama_rombel' => "XI IPS 2",
                'violation_score' => 1,
                'score' => 95,
                'register_type' => "Online",
                'school_origin' => "SMA Negeri 5",
                'birth_location' => "Medan",
                'birth_date' => "2002-06-18",
                'father_name' => "Daniel Miller",
                'father_job' => "Professor",
                'mother_name' => "Emma Miller",
                'mother_job' => "Artist",
                'guardian_name' => "George Brown",
                'guardian_job' => "Entrepreneur",
                'anak_keberapa' => 1,
                'height' => 180,
                'weight' => 70,
                'semester' => "Genap",
                'tingkat_pendidikan' => 12,
                'kurikulum' => "KTSP",
                'kebutuhan_khusus' => "Tidak ada",
            ],
        ];

        foreach($data as $student) Student::create($student);
    }
}
